// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rezxqmrmoauenjzfqmmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlenhxbXJtb2F1ZW5qemZxbW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzUyNjYsImV4cCI6MjA2MTE1MTI2Nn0.ZpWeMvuuT736WyoPsO_U7go7meMCO9cIYMLgczPl70E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);